### ISSUE TITLE
TypeError: Cannot read property 'end' of null

### ISSUE THREAD

**Issue by EvgenyOrekhov** [milewski/cross-port-killer#38]
```text
/app/node_modules/cross-port-killer/source/port-killer.js:41
        awk.stdin.end();
                  ^

TypeError: Cannot read property 'end' of null
    at Killer.linux (/app/node_modules/cross-port-killer/source/port-killer.js:41:19)
    at Killer.kill (/app/node_modules/cross-port-killer/source/port-killer.js:15:35)
    at exports.kill (/app/node_modules/cross-port-killer/source/index.js:5:56)
    at ChildProcess.startServer.on (/app/tests/run-tests.js:20:3)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

This started happening after I updated my dependencies. But the version of cross-port-killer stayed the same: 1.0.1.

Here is my `/app/tests/run-tests.js`

```js
const { spawn } = require('child_process');
const { kill } = require('cross-port-killer');

const env = Object.create(process.env);
env.BROWSER = 'none';
env.TEST = true;
// flag to prevent multiple test
let once = false;

const startServer = spawn(/^win/.test(process.platform) ? 'npm.cmd' : 'npm', ['start'], {
  env,
});

startServer.stderr.on('data', data => {
  // eslint-disable-next-line
  console.log(data.toString());
});

startServer.on('exit', () => {
  kill(process.env.PORT || 8000).then(() => process.exit());
});

// eslint-disable-next-line
console.log('Starting development server for e2e tests...');
startServer.stdout.on('data', data => {
  // eslint-disable-next-line
  console.log(data.toString());
  if (!once && data.toString().indexOf('Compiled successfully') >= 0) {
    // eslint-disable-next-line
    once = true;
    // eslint-disable-next-line no-console
    console.log('Development server is started, ready to run tests.');
    const testCmd = spawn(
      /^win/.test(process.platform) ? 'npm.cmd' : 'npm',
      ['test', '--', '--coverage'],
      {
        stdio: 'inherit',
      }
    );
    testCmd.on('exit', code => {
      startServer.kill();
      process.exitCode = code;
    });
  }
});
``` 

cross-port-killer version: 1.0.1
Node version: 11.11.0
OS: Ubuntu 18.10

**Comment by milewski** [comment]
Hi @EvgenyOrekhov , it seems to be an error with node11, i have pushed a new version `1.1.0` to npm can you have a try?

**Comment by EvgenyOrekhov** [comment]
@milewski It works now, thanks!
