### ISSUE TITLE
error: cross-port-killer

### ISSUE THREAD

**Issue by its-dibo** [milewski/cross-port-killer#69]
platform: linux

```
> kill-port 4200

events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn lsof ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn lsof',
  path: 'lsof',
  spawnargs: [ '-s', 'TCP:LISTEN', '-i', ':4200' ]
}
The terminal process "bash '-c', 'npm run kill-port'" terminated with exit code: 1.
```

**Comment by milewski** [comment]
I think your system does not have `lsof` somehow? perhaps a `apt install lsof` should solve it

see https://github.com/milewski/cross-port-killer/tree/1.4.0#dependencies
